const ErrorCodes = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",

  INVALID_MOCK_QUANTITY: "INVALID_MOCK_QUANTITY",
  MOCK_GENERATION_ERROR: "MOCK_GENERATION_ERROR",
  MOCK_DATABASE_ERROR: "MOCK_DATABASE_ERROR",

  INVALID_DATA: "INVALID_DATA",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};

export default ErrorCodes;